# Vagrantfile
# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.define 'fedora38' do |fedora|
    fedora.vm.box = 'generic/fedora38'
    fedora.vm.box_check_update = false
    # fedora.vm.hostname = 'fedora38-VM-pj'
    fedora.vm.hostname = 'fedora'
    fedora.vm.network 'private_network', type: 'dhcp'

    fedora.vm.provider :libvirt do |libvirt|
      libvirt.driver = 'kvm'
      libvirt.cpus = 2
      libvirt.memory = 2048
    end

    fedora.vm.provision 'ansible' do |ansible|
      ansible.playbook = './ansible/playbook.yml'
      ansible.compatibility_mode = '2.0'
      ansible.inventory_path = 'ansible/hosts'
      ansible.groups = ['fedora38']
    end
  end
end
