# Vagrantfile
# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box = 'bento/fedora-38'
  config.vm.box_check_update = false
  config.vm.hostname = 'fedora38-VM-pj'
  config.vm.network 'private_network', type: 'dhcp'

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = 'kvm'
    libvirt.cpus = 2
    libvirt.memory = 1024
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = './ansible/playbook.yml'
    ansible.compatibility_mode = '2.0'
  end
end
